//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automation.Plugins.YZ.Stocking.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1,23;2,0")]
        public string LED {
            get {
                return ((string)(this["LED"]));
            }
            set {
                this["LED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"1-小品种LED:select *,case status  when '1' then '已下单' else  '未下单' end orderstatus,'已经过' ledStatus from sms_supply_task where origin_position_address='14';2-扫码LED:select *,case status  when '1' then '已下单' else  '未下单' end orderstatus,'已经过' ledStatus from sms_supply_task")]
        public string LED_SQL {
            get {
                return ((string)(this["LED_SQL"]));
            }
            set {
                this["LED_SQL"] = value;
            }
        }
    }
}
